### ISSUE TITLE
add inline css instead of separate files

### ISSUE THREAD

**Issue by ghost** [s1lentp4nther/blj-blog#4]
apply this code to your index.php entrypoint file:

```css
<style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
    position: fixed;
    top: 0;
    width: 100%;
  }
  
  li {
    float: left;
    border-right:1px solid #bbb;
  }
  
  li:last-child {
    border-right: none;
  }
  
  li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
  }
</style>
```

can produce more efficient dom code
